### ISSUE TITLE
Under which license is this product provided?

### ISSUE THREAD

**Issue by cmplstofB** [lo48576/docbook-xhtml5#1]
Hello.

Under which license is this product provided?

**Comment by lo48576** [comment]
Hello.
Thank you for telling me the repo has no license file!

I added MIT license file just now (in <https://github.com/lo48576/docbook-xhtml5/commit/00f9f99b231036086930d0d5eba254b204dfc5b2>).
If you want another option, feel free to tell me.

**Comment by cmplstofB** [comment]
Thank you!
